<div class="jumbotron">
    <h2 style="float:left; margin-right:10px">Tarefas</h2>
    <a href="<?=$this->basePath()?>/tarefa/novo">
        <img alt="nova tarefa" src="<?=$this->basePath()?>/img/add.png">
    </a>
</div>
<?php
//monta a string com os registros no formato array do jquery p/ adicionar ao grid
$registros="[";
foreach ($this->projetos as $projeto):
	foreach ($projeto->getTarefas() as $tarefa):
		$registros .= "{
			id: '".$tarefa->getId()."', 
			projeto: '[".strtoupper($projeto->getNome())."]', 
			tarefa: '".$tarefa->getNome()."',
			vencimento: '".$tarefa->getVencimento()->format("Y/m/d")."'
		},";
	endforeach;
endforeach;
if ($this->tarefasPessoais):
    foreach ($this->tarefasPessoais as $tarefa):
        $registros .= "{
    		id: '".$tarefa->getId()."',
    		projeto: '[Tarefas Correlatas]',
    		tarefa: '".$tarefa->getNome()."',
    		vencimento: '".$tarefa->getVencimento()->format("Y/m/d")."'
    	},";
    endforeach;
endif;
$registros .= "]";
?>
<!-- quebra de linha -->
<style type="text/css">
table.ui-jqgrid-btable tbody tr td b{
        white-space: normal !important;
    }
</style>
<!-- adiciona os registros ao grid -->
<script type="text/javascript">
window.onload=function(){
	jQuery(document).ready(function(){
		jQuery("#gridtarefa").jqGrid('setGridParam',{data:<?=$registros?>}).trigger('reloadGrid');
	});
}
</script> 

<table id="gridtarefa" class="scroll"></table> 
<div id="paginacao"></div>
<div id="pesquisa"></div>