<form method='post'>
    <h2 style="float:left; margin-right:10px">Tarefas</h2>
	<input type="submit" value="gravar" formaction="<?=$this->basePath()?>/tarefa/grava" style="background-image: url('<?=$this->basePath()?>/img/check.png')" id="botao">
	<?php if($this->Url()!= $this->basePath().'/tarefa/novo'): ?>
		<input type="button" value="nova" OnClick="location.href='<?=$this->basePath()?>/tarefa/novo';" style="background-image: url('<?=$this->basePath()?>/img/add.png')" id="botao">
		<input type="button" value="excluir" OnClick="location.href='<?=$this->basePath()?>/tarefa/exclui/id/<?=$v ? $this->tarefa->getId() : "" ?>';" style="background-image: url('<?=$this->basePath()?>/img/del.png')" id="botao">
	<?php endif;?><br>
    <label>Nome:
        <input type="text" name="nome" placeholder="nome da tarefa" required value="<?=$v ? $this->tarefa->getNome() : "" ?>">
    </label><br>
    <label>Descrição:
        <textarea name="descricao" class="ckeditor" rows="2" cols="10" wrap="hard">
             <?=$v ? $this->tarefa->getDescricao() : "" ?>
        </textarea>
    </label><br>
    <label>Vencimento:
        <input type="date" name="vencimento" required 
            value="<?=$v ? $this->tarefa->getVencimento()->format("Y/m/d")
                   : "" ?>">
    </label><br>
    <?php if ($this->identity()[1]=="adm"): ?>
        <label style="float:left; padding:10px">Responsável:<br>
            <select name="responsavel" size="10">
                <?php foreach($this->usuarios as $usuario): ?>
                    <option 
                        <?=($v && $usuario==$this->tarefa->getUsuario()) ? "selected" : ""?> 
                        value="<?=$usuario->getId()?>">
                            <?=$usuario->getNome()?>
                    </option>
                <?php endforeach; ?>
            </select>
        </label>
    <?php endif; ?>
    <label>Projeto:<br>
        <select name="projeto" size="10" required>
            <?php foreach($this->projetos as $projeto): ?>
                <option 
                    <?=($v && $projeto==$this->tarefa->getProjeto()) ? "selected" : ""?>
                    value="<?=$projeto->getId()?>">
                        <?=$projeto->getNome()?>
                </option>
            <?php endforeach; ?>
        </select>
    </label>
    <input type="hidden" name="tarefa" value="<?=$v ? $this->tarefa->getId() : ""?>">
</form>