<?php

namespace MyClasses\Entities\Proxies\__CG__\MyClasses\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AclUsuario extends \MyClasses\Entities\AclUsuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'MyClasses\\Entities\\AclUsuario' . "\0" . 'id', '' . "\0" . 'MyClasses\\Entities\\AclUsuario' . "\0" . 'nome', '' . "\0" . 'MyClasses\\Entities\\AclUsuario' . "\0" . 'cargo', '' . "\0" . 'MyClasses\\Entities\\AclUsuario' . "\0" . 'login', '' . "\0" . 'MyClasses\\Entities\\AclUsuario' . "\0" . 'senha', '' . "\0" . 'MyClasses\\Entities\\AclUsuario' . "\0" . 'equipes', '' . "\0" . 'MyClasses\\Entities\\AclUsuario' . "\0" . 'projetos', '' . "\0" . 'MyClasses\\Entities\\AclUsuario' . "\0" . 'tarefas');
        }

        return array('__isInitialized__', '' . "\0" . 'MyClasses\\Entities\\AclUsuario' . "\0" . 'id', '' . "\0" . 'MyClasses\\Entities\\AclUsuario' . "\0" . 'nome', '' . "\0" . 'MyClasses\\Entities\\AclUsuario' . "\0" . 'cargo', '' . "\0" . 'MyClasses\\Entities\\AclUsuario' . "\0" . 'login', '' . "\0" . 'MyClasses\\Entities\\AclUsuario' . "\0" . 'senha', '' . "\0" . 'MyClasses\\Entities\\AclUsuario' . "\0" . 'equipes', '' . "\0" . 'MyClasses\\Entities\\AclUsuario' . "\0" . 'projetos', '' . "\0" . 'MyClasses\\Entities\\AclUsuario' . "\0" . 'tarefas');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AclUsuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function addEquipe(\MyClasses\Entities\AclPerfil $equipe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEquipe', array($equipe));

        return parent::addEquipe($equipe);
    }

    /**
     * {@inheritDoc}
     */
    public function delEquipe(\MyClasses\Entities\AclPerfil $equipe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'delEquipe', array($equipe));

        return parent::delEquipe($equipe);
    }

    /**
     * {@inheritDoc}
     */
    public function getEquipes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEquipes', array());

        return parent::getEquipes();
    }

    /**
     * {@inheritDoc}
     */
    public function addProjeto(\MyClasses\Entities\Projeto $projeto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProjeto', array($projeto));

        return parent::addProjeto($projeto);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjetos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjetos', array());

        return parent::getProjetos();
    }

    /**
     * {@inheritDoc}
     */
    public function addTarefa(\MyClasses\Entities\Tarefa $tarefa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTarefa', array($tarefa));

        return parent::addTarefa($tarefa);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarefas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarefas', array());

        return parent::getTarefas();
    }

    /**
     * {@inheritDoc}
     */
    public function getTarefasCorrelatas(array $idsProjetos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarefasCorrelatas', array($idsProjetos));

        return parent::getTarefasCorrelatas($idsProjetos);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function getCargo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCargo', array());

        return parent::getCargo();
    }

    /**
     * {@inheritDoc}
     */
    public function getLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogin', array());

        return parent::getLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function getSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenha', array());

        return parent::getSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function setCargo($cargo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCargo', array($cargo));

        return parent::setCargo($cargo);
    }

    /**
     * {@inheritDoc}
     */
    public function setLogin($login)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogin', array($login));

        return parent::setLogin($login);
    }

    /**
     * {@inheritDoc}
     */
    public function setSenha($senha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenha', array($senha));

        return parent::setSenha($senha);
    }

    /**
     * {@inheritDoc}
     */
    public function sets(array $atributos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'sets', array($atributos));

        return parent::sets($atributos);
    }

}
