<?php

namespace MyClasses\Entities\Proxies\__CG__\MyClasses\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AclPerfil extends \MyClasses\Entities\AclPerfil implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'MyClasses\\Entities\\AclPerfil' . "\0" . 'id', '' . "\0" . 'MyClasses\\Entities\\AclPerfil' . "\0" . 'perfil', '' . "\0" . 'MyClasses\\Entities\\AclPerfil' . "\0" . 'usuarios', '' . "\0" . 'MyClasses\\Entities\\AclPerfil' . "\0" . 'projetos', '' . "\0" . 'MyClasses\\Entities\\AclPerfil' . "\0" . 'recursos');
        }

        return array('__isInitialized__', '' . "\0" . 'MyClasses\\Entities\\AclPerfil' . "\0" . 'id', '' . "\0" . 'MyClasses\\Entities\\AclPerfil' . "\0" . 'perfil', '' . "\0" . 'MyClasses\\Entities\\AclPerfil' . "\0" . 'usuarios', '' . "\0" . 'MyClasses\\Entities\\AclPerfil' . "\0" . 'projetos', '' . "\0" . 'MyClasses\\Entities\\AclPerfil' . "\0" . 'recursos');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AclPerfil $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function addUsuario(\MyClasses\Entities\AclUsuario $usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsuario', array($usuario));

        return parent::addUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function delUsuario(\MyClasses\Entities\AclUsuario $usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'delUsuario', array($usuario));

        return parent::delUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarios', array());

        return parent::getUsuarios();
    }

    /**
     * {@inheritDoc}
     */
    public function addProjeto(\MyClasses\Entities\Projeto $projeto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProjeto', array($projeto));

        return parent::addProjeto($projeto);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjetos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjetos', array());

        return parent::getProjetos();
    }

    /**
     * {@inheritDoc}
     */
    public function addRecurso(\MyClasses\Entities\AclRecurso $recurso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRecurso', array($recurso));

        return parent::addRecurso($recurso);
    }

    /**
     * {@inheritDoc}
     */
    public function delRecurso(\MyClasses\Entities\AclRecurso $recurso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'delRecurso', array($recurso));

        return parent::delRecurso($recurso);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecursos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecursos', array());

        return parent::getRecursos();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getPerfil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerfil', array());

        return parent::getPerfil();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setPerfil($perfil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPerfil', array($perfil));

        return parent::setPerfil($perfil);
    }

    /**
     * {@inheritDoc}
     */
    public function sets(array $atributos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'sets', array($atributos));

        return parent::sets($atributos);
    }

}
