<div class="jumbotron">
    <h2 style="float:left; margin-right:10px">Projetos</h2>
    <a href="<?=$this->basePath()?>/projeto/novo">
        <img alt="novo projeto" src="<?=$this->basePath()?>/img/add.png">
    </a>
</div>
<?php
//monta a string com os registros no formato array do jquery p/ adicionar ao grid
$registros="[";
foreach ($this->projetos as $projeto):
		$registros .= "{
			id: '".$projeto->getId()."',
			nome: '".$projeto->getNome()."',
			vencimento: '".$projeto->getVencimento()."'
		},";
endforeach;
$registros .= "]";
?>
<!-- quebra de linha -->
<style type="text/css">
table.ui-jqgrid-btable tbody tr td b{
        white-space: normal !important;
    }
</style>
<!-- adiciona os registros ao grid -->
<script type="text/javascript">
window.onload=function(){
	jQuery(document).ready(function(){
		jQuery("#gridprojeto").jqGrid('setGridParam',{data:<?=$registros?>}).trigger('reloadGrid');
	});
}
</script> 

<table id="gridprojeto" class="scroll"></table> 
<div id="paginacao"></div>
<div id="pesquisa"></div>