<h2>
<?php if ($this->nome): ?>
            Seja bem vindo <b><?=$this->nome?></b>
            <p>redirecionando para seu painel administrativo...</p>
<script>
    setTimeout(function() { 
        location.href="<?=$this->url('Locador/imovel')?>";
    }, 2000);
</script>
<?php else: ?>
            <?=$this->partial("formLogin")?>
            <i style="color: gray"><?=$this->erro?></i>
<?php endif ?>
</h2>