<!doctype html>
<head>
    <title>Imobiliaria Virtual</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" href='<?= $this->basePath() ?>/img/favicon.ico' />
    <link rel="stylesheet" type="text/css" href='<?= $this->basePath() ?>/css/locador.css' />
    <script src="<?= $this->basePath() ?>/js/jquery-1.11.2.min.js"></script>
</head>
<body>
    <nav role="navigation">
        <div id="header">
            <div id="menu">
                <?php if (isset($this->locador)): ?>
                <ul>
                    <li class="current_page_item"><a href="<?= $this->basePath() ?>/Locador/imovel/novo/1">+imovel</a></li>
                </ul>
                <?php endif; ?>
            </div>
            <div id="logo">
                <a href="<?= $this->basePath() ?>/">
                    <img alt="" src="<?= $this->basePath() ?>/img/ic_launcher-web.png" style="float:left">
                    <h1>imobiliari@</h1>
                </a>
                <div class="pesquisa">
                    <h2>LOCADOR - Painel Administrativo</h2>
                </div>
            </div>
        </div>
    </nav>
    <aside>
        <ul><h2>AVISOS</h2>
            <li><a href="<?=$this->basePath()?>/Locador/visita">Visitas(<?=$this->visitas?>)</a></li>
        </ul>
    </aside>
    <main>
        <div id="page">
            <div id="page-bgtop">
                <div id="page-bgbtm">
                    <?= $this->content; ?>
                    <div style="clear: both;">&nbsp;</div>
                </div>
                <!-- end #page -->
            </div>
        </div>                
    </main>
    <footer>
        <div id="footer-bgcontent">
            <div id="footer">
                <p>&copy; Todos os direitos reservados <a href="http://grupo-gpa.com" rel="nofollow">Grupo GPA</a>.</p>
            </div>
            <!-- end #footer -->
        </div>
    </footer>
</body>
</html>