<script src="https://maps.googleapis.com/maps/api/js"></script>
<script>
    var mapa;
    function criaMapa() {
        var posicao = new google.maps.LatLng(<?=$this->imovel->getLatitude()?>, <?=$this->imovel->getLongitude()?>);
        var opcoesMapa = {
            zoom: 15,
            disableDefaultUI: true,
            center: posicao
        };
        mapa = new google.maps.Map(document.getElementById('mapa'),opcoesMapa);        
        marcaLocalizacao(posicao, mapa);
    }
    google.maps.event.addDomListener(window, 'load', criaMapa);
    function marcaLocalizacao(posicao, mapa) {
        marcador = new google.maps.Marker({
            position: posicao,
            map: mapa
        });
        mapa.panTo(posicao);
    }
</script>

<div id="etapas">
    <div class="etapa"><a href="#"><label>1-</label> tour virtual</a></div>
    <div class="etapa"><a href="#"><label>2-</label> agende uma visita</a></div>
    <div class="etapa" style="border-bottom:5px solid #fff"><a href="#"><label>3-</label> ficha de visita</a></div>
    <div class="etapa"><a href="#"><label>4-</label> contrato</a></div>
</div>

<div id="conteudo">
    <h2>Ficha de Visita</h2>
    <div id="mapa" style="width:500px;float:left"></div>
    <p>
        <?php
            switch ($this->imovel->getTipo()):
                case "c": echo "Casa "; break;
                case "a": echo "Ap "; break;
                case "m": echo "Comercio "; break;
                case "t": echo "Terreno "; break;
                case "f": echo "Fazenda "; break;
            endswitch;
            echo $this->imovel->getQtdQuartos()."/4";
            ?><br>
            Locador: <?php
            if ($this->imovel->getLocador()!=null):
                echo $this->imovel->getLocador()->getNome(); 
            endif; ?>
        <input type="button" value="imprimir">
    </p>
</div>