<table id="pesquisa">
    <thead>
    </thead>
    <tbody>
        <?php foreach ($this->imoveis as $imovel): ?>
        <tr onClick="location.href='<?=$this->url('imovel/visualiza',array('id'=>1))?>';">
            <td><img src="<?=$this->basePath()?>/img/<?=$imovel->getId()?>.jpg"></td>
            <td><?=$imovel->getDescricao()?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
    <tfoot>
    </tfoot>
</table>