<script src="<?=$this->basePath()?>/js/jquery.zoom.min.js"></script>
<script src="<?=$this->basePath()?>/js/jquery.jcarousellite.min.js"></script>
<script src="<?=$this->basePath()?>/js/jqModal.js"></script>
<link rel="stylesheet" type="text/css" href='<?= $this->basePath() ?>/css/jqModal.css' />
<script>
    $(document).ready(function () {
        $('.zoom').zoom();
        $('#jqModal').jqm();
        $(".fotos").jCarouselLite({
            btnNext: ".proximo",
            btnPrev: ".anterior",
            auto: 5000,
            speed: 2000,
            visible: 1
        });
    });
</script>

<div id="etapas">
    <div class="etapa" style="border-bottom: 5px solid #fff"><a href="#"><label>1-</label> tour virtual</a></div>
    <div class="etapa"><a href="#"><label>2-</label> agende uma visita</a></div>
    <div class="etapa"><a href="#"><label>3-</label> ficha de visita</a></div>
    <div class="etapa"><a href="#"><label>4-</label> contrato</a></div>
</div>

<div id="conteudo">
    <div class="fotos" style="float:left">
        <ul>
            <li class="zoom">
                <img src="<?= $this->basePath() ?>/arquivos/imoveis/img/<?=$this->imovel->getId()?>/1.jpg" width="400" height="300">
            </li>
            <li class="zoom">
                <img src="<?= $this->basePath() ?>/arquivos/imoveis/img/<?=$this->imovel->getId()?>/2.jpg" width="400" height="300">
            </li>
            <li class="zoom">
                <img src="<?= $this->basePath() ?>/arquivos/imoveis/img/<?=$this->imovel->getId()?>/3.jpg" width="400" height="300">
            </li>
            <li class="zoom">
                <img src="<?= $this->basePath() ?>/arquivos/imoveis/img/<?=$this->imovel->getId()?>/4.jpg" width="400" height="300">
            </li>
            <li class="zoom">
                <img src="<?= $this->basePath() ?>/arquivos/imoveis/img/<?=$this->imovel->getId()?>/5.jpg" width="400" height="300">
            </li>
        </ul>
    <button class="anterior"><</button>
    <button class="proximo">></button>
    </div>
    <div class="jqmWindow" id="jqModal">
        <!--<div id="janela">
            <p class="controle">X</p>-->
        <?php include '../imobiliaria/module/Application/view/application/usuario/form.phtml'; ?>
    </div>
    <div id="informacoes">
        <h2><?php
            switch ($this->imovel->getTipo()):
                case "c": echo "Casa "; break;
                case "a": echo "Ap "; break;
                case "m": echo "Comercio "; break;
                case "t": echo "Terreno "; break;
                case "f": echo "Fazenda "; break;
            endswitch;
            echo $this->imovel->getQtdQuartos()."/4";
        ?></h2><br>
        <?php if (isset($this->mais)): ?>
            <p><?=$this->imovel->getDescricao()?>
                <input type="button" value="quero visitar" onclick="location.href = '<?= $this->basePath() ?>/imovel/agendavisita/id/<?=$this->imovel->getId()?>';">
            </p>
        <?php else: ?>
            <p><?=substr($this->imovel->getDescricao(), 0, 10)?>...</p><br>
            <input type="button" value="+informaçoes" class="jqModal"> <!--class="controle"-->
        <?php endif; ?>
    </div>
</div>