<div class="jumbotron">
    <h2 style="float:left; margin-right:10px">Equipes</h2>
    <a href="<?=$this->basePath()?>/equipe/novo">
        <img alt="nova equipe" src="<?=$this->basePath()?>/img/add.png">
    </a>
</div>
<?php
//monta a string com os registros no formato array do jquery p/ adicionar ao grid
$registros="[";
foreach ($this->perfis as $perfil):
    if ($perfil->getUsuarios()->isEmpty())
        $registros .= "{
			id: '".$perfil->getId()."',
			perfil: '[".strtoupper($perfil->getPerfil())."]',
			usuario: '-',
			cargo: '-'
		},";
    else
    	foreach ($perfil->getUsuarios() as $usuario):
    		$registros .= "{
    			id: '".$perfil->getId()."', 
    			perfil: '[".strtoupper($perfil->getPerfil())."]', 
    			usuario: '".$usuario->getNome()."',
    			cargo: '".$usuario->getCargo()."'
    		},";
    	endforeach;
endforeach;
$registros .= "]";
?>
<!-- quebra de linha -->
<style type="text/css">
table.ui-jqgrid-btable tbody tr td b{
        white-space: normal !important;
    }
</style>
<!-- adiciona os registros ao grid -->
<script type="text/javascript">
window.onload=function(){
	jQuery(document).ready(function(){
		jQuery("#gridperfil").jqGrid('setGridParam',{data:<?=$registros?>}).trigger('reloadGrid');
	});
}
</script> 

<table id="gridperfil" class="scroll"></table> 
<div id="paginacao"></div>
<div id="pesquisa"></div>