<script src="<?=$this->basePath()?>/js/ajax.js"></script>

<form id="formulario" method="post" style="margin-top: 20px">
    <h2>Faça login para cadastrar seu imovel ou clique <a href="<?=$this->basePath()?>/locador/novo">aqui</a> caso ainda nao seja cadastrado</h2>
    <div id="aguarde">
        <img src="<?=$this->basePath()?>/img/loading.gif" class="icon" style="float:left" width="48" height="48" alt="#"/>
        aguarde...
    </div>
    <label for="login">Usuario:</label>
    <input type="text" name="login" id="login" placeholder="seu login" required="">
    <label for="senha">Senha</label>
    <input type="password" name="senha" id="senha" placeholder="sua senha" required="">
    <input type="button" value="acessar" OnClick="ajax(
                                                        '<?=$this->url('Locador/login')?>',
                                                        'POST',
                                                        {   login:$('#formulario input:text[name=login]').val(),
                                                            senha:$('#formulario input:password[name=senha]').val()
                                                        }
                                                    );">
    <a href="<?=$this->basePath()?>/locador/novo">ainda nao sou cadastrado</a>
</form>