<!doctype html>
    <head>
        <title>Imobiliaria Virtual</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="shortcut icon" href='<?=$this->basePath()?>/img/favicon.ico' />
        <link rel="stylesheet" type="text/css" href='<?=$this->basePath()?>/css/style.css' />        
        <script src="<?=$this->basePath()?>/js/jquery-1.11.2.min.js"></script>
    </head>
    <body>
        <nav role="navigation">
			<div id="header">
				<div id="menu">
					<ul>
                        <li class="current_page_item"><a href="#">Quem Somos</a></li>
						<li class="current_page_item"><a href="#">Alugar</a></li>
						<li class="current_page_item"><a href="#">Comprar</a></li>
						<li class="current_page_item"><a href="#">Anunciar</a></li>
						<li class="current_page_item"><a href="#" style="border-right: none">Contato</a></li>
                    </ul>
				</div>
				<div id="logo">
					<a href="<?=$this->basePath()?>">
						<img alt="" src="./img/ic_launcher-web.png" style="float:left">
						<h1>imobiliari@</h1>
					</a>
                    <div class="pesquisa">
                        <input type="search" placeholder="ex: casa 2 quartos, ap centro">
                        <input type="button" value=">">
                    </div>
				</div>
			</div>
        </nav>
            <main>
                <div id="page">
					<div id="page-bgtop">
						<div id="page-bgbtm">			
				                <?=$this->content;?>
							<div style="clear: both;">&nbsp;</div>
						</div>
						<!-- end #page -->
					</div>
				</div>                
            </main>
            <aside>
            </aside>
            <footer>
                <div id="footer-bgcontent">
					<div id="footer">
						<p>&copy; Todos os direitos reservados <a href="http://grupo-gpa.com" rel="nofollow">Grupo GPA</a>.</p>
					</div>
					<!-- end #footer -->
				</div>
            </footer>
    </body>
</html>