<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <title>GPA Engenharia</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="shortcut icon" href='<?php echo $this->basePath(); ?>/img/favicon.ico' />
        <link rel="stylesheet" type="text/css" href='<?php echo $this->basePath(); ?>/css/tudo.min.css' />
        <script async defer type="text/javascript" src="<?php echo $this->basePath(); ?>/js/tudo.min.js"></script> <!-- async defer  -->
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('GPA Engenharia') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        <?php if ($this->nome): ?>
                            <li class="active"><a href="<?php echo $this->url('tarefa') ?>"><?php echo $this->translate('Tarefas') ?></a></li>
                            <li class="active"><a href="<?php echo $this->url('usuario') ?>"><?php echo $this->translate('Usuários') ?></a></li>
                            <li class="active"><a href="<?php echo $this->url('conf') ?>"><?php echo $this->translate('Configurações') ?></a></li>
                            <li class="active"><a href="<?php echo $this->url('logoff') ?>"><span id="logoff"><?php echo $this->translate('Logoff') ?></span></a></li>
                        <?php endif; ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <main>
                <?php echo $this->content; ?>
            </main>
            <aside>
            </aside>
            <footer>
                <hr>
                <p>&copy; - <?php echo date('Y') ?> GPA Engenharia. Todos os direitos reservados.</p>
            </footer>
        </div> <!-- /container -->
    </body>
</html>