<form action="<?= $this->basePath() ?>/imovel/visualiza/id/1/mais" method="post" id="formulario">
    <h2>Cadastre-se para ter acesso a mais informaçoes</h2>
    <label for="nome">Nome:</label>
    <input type="text" id="nome" name="nome">
    <label for="email">E-mail:</label>
    <input type="text" id="email" name="email">
    <label for="telefone">Telefone:</label>
    <input type="text" id="telefone" name="telefone">	
    <input type="submit" value="confirmar">	
</form>