<div class="jumbotron">
    <h2 style="float:left; margin-right:10px">Usuários</h2>
    <a href="<?=$this->basePath()?>/usuario/novo">
        <img alt="novo usuário" src="<?=$this->basePath()?>/img/add.png">
    </a>
</div>
<?php
//monta a string com os registros no formato array do jquery p/ adicionar ao grid
$registros="[";
foreach ($this->usuarios as $usuario):
	$registros .= "{
		id: '".$usuario->getId()."', 
		perfil: '[";
        $equipes = null;
		foreach ($usuario->getEquipes() as $equipe)
		    $equipes[] = $equipe->getPerfil();
		$registros .= implode($equipes, ",")."]', 
		usuario: '".$usuario->getNome()."',
		cargo: '".$usuario->getCargo()."'
	},";
endforeach;
$registros .= "]";
?>
<!-- quebra de linha -->
<style type="text/css">
table.ui-jqgrid-btable tbody tr td b{
        white-space: normal !important;
    }
</style>
<!-- adiciona os registros ao grid -->
<script type="text/javascript">
window.onload=function(){
	jQuery(document).ready(function(){
		jQuery("#gridusuario").jqGrid('setGridParam',{data:<?=$registros?>}).trigger('reloadGrid');
	});
}
</script> 

<table id="gridusuario" class="scroll"></table> 
<div id="paginacao"></div>
<div id="pesquisa"></div>