<div id="etapas">
    <div class="etapa"><a href="#"><label>1-</label> tour virtual</a></div>
    <div class="etapa"><a href="#"><label>2-</label> agende uma visita</a></div>
    <div class="etapa" style="border-bottom:5px solid #fff"><a href="#"><label>3-</label> ficha de visita</a></div>
    <div class="etapa"><a href="#"><label>4-</label> contrato</a></div>
</div>

<div id="conteudo">
    <h2>Ficha de Visita</h2>
    <img src="<?= $this->basePath() ?>/img/mapa.gif" style="float:left">
    <p>
        Imovel: Casa 2/4, garagem<br>
        Locador: Picashu Choque do Trovao<br>
        Endereço: R. 10, nº 100, Bairro Centro<br>
        <input type="button" value="imprimir">
    </p>
</div>