<script src="<?= $this->basePath() ?>/js/jquery.validate.js" type="text/javascript"></script>
<script async defer type="text/javascript" src="<?=$this->basePath()?>/js/ckeditor/ckeditor.js"></script>

<div id="etapas">
    <div class="etapa"><a href="#"><label>1-</label>Estrutura</a></div>
    <div class="etapa"><a href="#"><label>2-</label>Localizaçao</a></div>
    <div class="etapa"><a href="#"><label>3-</label>Fotos</a></div>
    <div class="etapa"><a href="#"><label>4-</label>Valores</a></div>
    <div class="etapa" style="border-bottom: 5px solid #fff"><a href="#"><label>5-</label>Resumo</a></div>
</div>

<form action="<?= $this->basePath() ?>/Locador/imovel/grava" method="post" id="formulario">
    <h2>Redija um resumo do seu imovel:</h2><br>
    <textarea name="descricao" rows="2" cols="10" placeholder="resumo" class="ckeditor" wrap="hard"></textarea><br>
    <label for="horariosVisita">Qual horario disponivel para visitaçao?</label>
    <input type="time" name="horariosVisita" style="width:100px">
    <input type="submit" value="finalizar">
</form>