<link rel="stylesheet" type="text/css" href="<?=$this->basePath()?>/css/jquery.Jcrop.css" />
<script type="text/javascript" src="<?=$this->basePath()?>/js/jquery.Jcrop.js"></script>
<script>
    window.onload=function(){
        function coordenadas(c){
            $('#x').val(Math.round(c.x));
            $('#y').val(Math.round(c.y));
            $('#w').val(Math.round(c.w));
            $('#h').val(Math.round(c.h));
            $('#coordenadas').html(Math.round(c.w)+' X '+Math.round(c.h));
        };
        $('#fotoFachada').Jcrop({
            onChange: coordenadas,
            minSize: [600,450],
            aspectRatio: 600/450,
            setSelect: [50,50,100,100],
            bgColor: 'transparent'
        });
    }
</script>

<div id="etapas">
    <div class="etapa"><a href="#"><label>1-</label>Estrutura</a></div>
    <div class="etapa"><a href="#"><label>2-</label>Localizaçao</a></div>
    <div class="etapa" style="border-bottom: 5px solid #fff"><a href="#"><label>3-</label>Fotos</a></div>
    <div class="etapa"><a href="#"><label>4-</label>Valores</a></div>
    <div class="etapa"><a href="#"><label>5-</label>Resumo</a></div>
</div>

<form action="<?= $this->basePath() ?>/Locador/imovel/upload" enctype="multipart/form-data" method="post" id="formulario">
    <h2>Mostre seu imovel</h2>
    <a href="#" onClick="$('#fachada').click();" id="addFoto">+adicionar foto</a>
    <input type="file" id="fachada" name="fachada" onchange="$('#formulario').submit();" style="visibility:hidden">
</form>

<div id="coordenadas" style="width:100px;font-size:18px;font-weight:bolder;margin-left:30%;border:1px solid yellow;"></div>
<form id="formulario" method="post" action="<?=$this->basePath()?>/Locador/imovel/novo/3">
    <input type="submit" value="finalizar recorte">
    <input type="hidden" id="x" name="x0" />
    <input type="hidden" id="y" name="y0" />
    <input type="hidden" id="w" name="w0" />
    <input type="hidden" id="h" name="h0" />
    <div style="float:left;margin-right:30px">
        <img src="<?=$this->basePath()?>/arquivos/imoveis/img/<?=$this->locador->getId()?>/<?=count($this->arquivos)==0?1:(count($this->arquivos)-2)?>.jpg?<?=rand(1,1000)?>" id="fotoFachada">
    </div>
</form>

<?php if (isset($this->arquivos)):
     foreach ($this->arquivos as $arquivo): ?>
        <img src="<?=$this->basePath().'/arquivos/imoveis/img/'.$this->locador->getId().'/'.$arquivo?>">
     <?php endforeach; ?>
<?php endif; ?>

<input type="button" value="proximo" onclick="location.href='<?=$this->basePath()?>/Locador/imovel/novo/4';">