<script src="<?= $this->basePath() ?>/js/jquery.validate.js" type="text/javascript"></script>
<script>
    $(document).ready(function(){
        jQuery.extend(jQuery.validator.messages, {
            required: "Preencha este campo!",
            date: "data invalida!"
        });
    });	
</script>

<div id="etapas">
    <div class="etapa" style="border-bottom: 5px solid #fff"><a href="#"><label>1-</label>Estrutura</a></div>
    <div class="etapa"><a href="#"><label>2-</label>Localizaçao</a></div>
    <div class="etapa"><a href="#"><label>3-</label>Fotos</a></div>
    <div class="etapa"><a href="#"><label>4-</label>Valores</a></div>
    <div class="etapa"><a href="#"><label>5-</label>Resumo</a></div>
</div>

<form action="<?= $this->basePath() ?>/Locador/imovel/novo/2" method="post" id="formulario">
    <h2>Qual a estrutura fisica do seu imovel?</h2><br>
    <div class="radio">
        <input type="radio" id="tipo" name="tipo" value="c" checked="" style="width:40px"><label>Casa</label>
    </div>
    <div class="radio">
        <input type="radio" name="tipo" value="a" style="width:30px"><label>Apartamento</label>
    </div>
    <div class="radio">
        <input type="radio" name="tipo" value="m" style="width:30px"><label>Comercio</label>
    </div>
    <div class="radio">
        <input type="radio" name="tipo" value="t" style="width:30px"><label>Terreno</label>
    </div>
    <div>
        <input type="radio" name="tipo" value="f" style="width:30px"><label>Fazenda</label>
    </div><br>
    
    <div style="float:left;margin-right:30px">
        <label for="areaLote">Area Total (m²):</label>
        <input type="number" id="areaLote" name="areaLote" value="360" required="" min="100" max="1000" step="10" style='width:120px'>
    </div>
    <div style="margin-right:30px">
        <label for="areaConstruida">Area Construida (m²):</label>
        <input type="number" id="areaConstruida" name="areaConstruida" value="180" required="" min="100" max="1000" step="10" style='width:120px'>
    </div><br>
    
    <div style="float:left;margin-right:30px">
        <label for="qtdComodos">Comodos:</label>
        <input type="number" id="qtdComodos" name="qtdComodos" value="5" required="" min="1" max="50" step="1" style='width:60px'>
    </div>
    <div style="float:left;margin-right:30px">
        <label for="qtdQuartos">Quartos:</label>
        <input type="number" id="qtdQuartos" name="qtdQuartos" value="2" required="" min="1" max="50" step="1" style='width:60px'>
    </div>
    <div style="float:left;margin-right:30px">
        <label for="qtdSuites">Suites:</label>
        <input type="number" id="qtdSuites" name="qtdSuites" value="1" required="" min="1" max="50" step="1" style='width:60px'>
    </div>
    <div style="float:left;margin-right:30px">
        <label for="qtdBanheiros">Banheiros:</label>
        <input type="number" id="qtdBanheiros" name="qtdBanheiros" value="1" required="" min="1" max="50" step="1" style='width:60px'>
    </div>
    <div style="margin-right:30px">
        <label for="qtdGaragens">Garagens:</label>
        <input type="number" id="qtdGaragens" name="qtdGaragens" value="1" required="" min="1" max="10" step="1" style='width:60px'>
    </div><br>        
    <div class="radio">
        <input type="radio" name="condominio" value="1" checked="" style="width:30px"><label>Condominio</label>
    </div>
    <div class="radio">
        <input type="radio" name="condominio" value="0" style="width:30px"><label>S/ condominio</label>
    </div>
    <div style="margin-right:30px;float:left">
        <label for="condominioAreasComuns">Areas comuns:</label>
        <textarea name="condominioAreasComuns" id="condominioAreasComuns" rows="5" cols="20" placeholder="piscina, churrasqueira"></textarea>
    </div>
    <div style="margin-right:30px">
        <label for="condominioAreasPrivativas">Areas privativas:</label>
        <textarea name="condominioAreasPrivativas" id="condominioAreasPrivativas" rows="5" cols="20" placeholder="salao, sauna"></textarea>
    </div><br>
    <div style="margin-right:30px">
        <label for="idade">Qual a idade do seu imovel?</label>
        <input type="number" id="idade" name="idade" value="1" required="" min="1" max="100" step="1" style='width:60px'>
    </div>
    <input type="submit" value="proximo">
</form>