<script src="https://maps.googleapis.com/maps/api/js"></script>
	    <script>
			var estilo = [
			              {
			            	    "featureType": "administrative.land_parcel",
			            	    "stylers": [
			            	      { "visibility": "off" }
			            	    ]
			            	  },{
			            	    "featureType": "administrative.neighborhood",
			            	    "stylers": [
			            	      { "visibility": "off" }
			            	    ]
			            	  },{
			            	    "featureType": "landscape.man_made",
			            	    "stylers": [
			            	      { "visibility": "off" }
			            	    ]
			            	  },{
			            	    "featureType": "landscape.natural",
			            	    "stylers": [
			            	      { "visibility": "off" }
			            	    ]
			            	  },{
			            	    "featureType": "poi.attraction",
			            	    "stylers": [
			            	      { "visibility": "off" }
			            	    ]
			            	  },{
			            	    "featureType": "poi.business",
			            	    "stylers": [
			            	      { "visibility": "off" }
			            	    ]
			            	  },{
			            	    "featureType": "poi.government",
			            	    "stylers": [
			            	      { "visibility": "off" }
			            	    ]
			            	  },{
			            	    "featureType": "poi.medical",
			            	    "stylers": [
			            	      { "visibility": "off" }
			            	    ]
			            	  },{
			            	    "featureType": "poi.park",
			            	    "stylers": [
			            	      { "visibility": "off" }
			            	    ]
			            	  },{
			            	    "featureType": "poi.place_of_worship",
			            	    "stylers": [
			            	      { "visibility": "off" }
			            	    ]
			            	  },{
			            	    "featureType": "poi.school",
			            	    "stylers": [
			            	      { "visibility": "off" }
			            	    ]
			            	  },{
			            	    "featureType": "poi.sports_complex",
			            	    "stylers": [
			            	      { "visibility": "off" }
			            	    ]
			            	  },{
			            	    "featureType": "road.highway",
			            	    "stylers": [
			            	      { "visibility": "off" }
			            	    ]
			            	  },{
			            	    "featureType": "road.arterial",
			            	    "stylers": [
			            	      { "visibility": "off" }
			            	    ]
			            	  },{
			            	    "featureType": "road.local",
			            	    "elementType": "labels.text",
			            	    "stylers": [
			            	      { "visibility": "off" }
			            	    ]
			            	  },{
			            	    "featureType": "transit",
			            	    "stylers": [
			            	      { "visibility": "off" }
			            	    ]
			            	  },{
			            	    "featureType": "water",
			            	    "stylers": [
			            	      { "visibility": "off" }
			            	    ]
			            	  },{
			            	    "stylers": [
			            	      { "hue": "#1900ff" },
			            	      { "saturation": 97 }
			            	    ]
			            	  }
			            	];
	    	var mapa;
			function criaMapa() {
				var mapaEstilizado = new google.maps.StyledMapType(estilo,
					    {name: "imoveis em Rio Verde"});
				var mapaCanvas = document.getElementById('mapa');
				var latLng = new google.maps.LatLng(-17.7913301,-50.9322535,14);
				var opcoesMapa = {
					center: latLng,
					zoom: 14,
					disableDefaultUI: true,
					disableDoubleClickZoom: true,
					keyboardShortcuts: false,
					mapTypeControlOptions: {
					      mapTypeIds: [google.maps.MapTypeId.ROADMAP, 'map_style']
					    }
				};
				mapa = new google.maps.Map(mapaCanvas, opcoesMapa);
				for (var i=0; i<=0.009; (i=i+0.001)){
					var latLng = new google.maps.LatLng( -17.7993301+i, -50.9322535+i);
			        var marcadorCasa = new google.maps.Marker({
			          position: latLng,
			          map: mapa,
			          icon: './img/casa.png',
			          //title: '3/4, 2 garagens'
			        });
					var infoCasa = new google.maps.InfoWindow({
					      content: "<div class='marcadorCasa'>"+
                                        "<a href='#' OnClick='identifiquese();'>"+
                                            "<img src='./img/casa.jpg' alt='+informaçoes'><br>"+
                                            "2/4, suite, 360m²"+
                                        "</a>"+
                                    "</div>"
					  });
			        google.maps.event.addListener(marcadorCasa, 'mouseover', function() {
			        	infoPredio.close(mapa,this);
			        	infoCasa.close(mapa,this);
			        	infoCasa.open(mapa,this);
		          	});
			        /* google.maps.event.addListener(marcadorCasa, 'mouseout', function() {
			        	window.setTimeout(function() {
			        		infoCasa.close(mapa,this);
			        	},1000);
		          	}); */
				}
				for (var i=0; i<=0.009; (i=i+0.001)){
					var latLng = new google.maps.LatLng( -17.7993301+i, -50.9372535+i);
			        var marcadorPredio = new google.maps.Marker({
			          position: latLng,
			          map: mapa,
			          icon: './img/predio.png',
			          //title: '3/4, 2 garagens'
			        });
					var infoPredio = new google.maps.InfoWindow({
					      content: "<div class='marcadorAp'>"+
                                        "<a href='#' OnClick='identifiquese();'>"+
                                            "<img src='./img/predio.jpg' alt='+informaçoes'><br>"+
                                            "3/4, suite, varanda"+
                                        "</a>"+
                                    "</div>"
					  });
			        google.maps.event.addListener(marcadorPredio, 'mouseover', function() {
				        infoCasa.close(mapa,this);
			        	infoPredio.close(mapa,this);
			        	infoPredio.open(mapa,this);
		          	});
				}
		        google.maps.event.addListener(mapa, 'mouseout', function() {
	        		infoPredio.close(mapa,this);
	        		infoCasa.close(mapa, this);
	          	});
				mapa.mapTypes.set('map_style', mapaEstilizado);
				mapa.setMapTypeId('map_style');
				//mapa.data.loadGeoJson('mapa.json');
			}
			google.maps.event.addDomListener(window, 'load', criaMapa);
            function identifiquese(){
                var nome = prompt("Seu nome:");
                if (nome != null)
                    location.href = "<?=$this->url('imovel/visualiza',array('id'=>1))?>";
            }
	    </script>
<!-- <iframe id="mapa"
  src="https://www.google.com/maps/embed/v1/place?
key=AIzaSyB553Rmi0_KI5Lazgig92dDj11t0yVlreY
  &q=St.+Industrial,+Rio+Verde+-+GO,+75905-020">
</iframe> -->
<div id="mapa"></div>
<div id="content">
	<div class="post">
		<p class="meta"><span class="date">Sunday, January 26, 2011</span> 7:27 AM Posted by <a href="#">Someone</a></p>
		<h2 class="title"><a href="#">Lorem ipsum sed aliquam</a></h2>
		<div class="entry">
			<p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec   consectetuer. Donec ipsum. Proin imperdiet est. Phasellus <a href="#">dapibus semper urna</a>. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc, ut consectetuer nisl felis ac diam. Etiam non felis. Donec ut ante. In id eros.</p>
		</div>
		<div><a href="#" class="links">View Full Story</a></div>
	</div>
	<div class="post">
		<p class="meta"><span class="date">Sunday, January 26, 2011</span> 7:27 AM Posted by <a href="#">Someone</a></p>
		<h2 class="title"><a href="#">Lorem ipsum sed aliquam</a></h2>
		<div class="entry">
			<p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec   consectetuer. Donec ipsum. Proin imperdiet est. Phasellus <a href="#">dapibus semper urna</a>. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc, ut consectetuer nisl felis ac diam. Etiam non felis. Donec ut ante. In id eros.</p>
		</div>
		<div><a href="#" class="links">View Full Story</a></div>
	</div>
	<div class="post">
		<p class="meta"><span class="date">Sunday, January 26, 2011</span> 7:27 AM Posted by <a href="#">Someone</a></p>
		<h2 class="title"><a href="#">Lorem ipsum sed aliquam</a></h2>
		<div class="entry">
			<p>Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Phasellus <a href="#">dapibus semper urna</a>. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc, ut consectetuer nisl felis ac diam. </p>
		</div>
		<div><a href="#" class="links">View Full Story</a></div>
	</div>
</div>
<!-- end #content -->
<div id="sidebar">
	<ul>
		<li>
			<h2>Aliquam tempus</h2>
			<p>Mauris vitae nisl nec metus placerat perdiet est. Phasellus dapibus semper urna. Pellentesque ornare, orci in consectetuer hendrerit, volutpat.</p>
		</li>
		<li>
			<h2>Pellenteque ornare </h2>
			<ul>
				<li><a href="#">Nec metus sed donec</a></li>
				<li><a href="#">Magna lacus bibendum mauris</a></li>
				<li><a href="#">Velit semper nisi molestie</a></li>
				<li><a href="#">Eget tempor eget nonummy</a></li>
				<li><a href="#">Nec metus sed donec</a></li>
				<li><a href="#">Velit semper nisi molestie</a></li>
				<li><a href="#">Eget tempor eget nonummy</a></li>
				<li><a href="#">Nec metus sed donec</a></li>
			</ul>
		</li>
		<li>
			<h2>Turpis nulla</h2>
			<ul>
				<li><a href="#">Nec metus sed donec</a></li>
				<li><a href="#">Magna lacus bibendum mauris</a></li>
				<li><a href="#">Velit semper nisi molestie</a></li>
				<li><a href="#">Eget tempor eget nonummy</a></li>
				<li><a href="#">Nec metus sed donec</a></li>
				<li><a href="#">Nec metus sed donec</a></li>
				<li><a href="#">Magna lacus bibendum mauris</a></li>
				<li><a href="#">Velit semper nisi molestie</a></li>
				<li><a href="#">Eget tempor eget nonummy</a></li>
				<li><a href="#">Nec metus sed donec</a></li>
			</ul>
		</li>
	</ul>
</div>
<!-- end #sidebar -->